/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_b2bpo_media_ffmpegTest_VideoBrowser */

#ifndef _Included_com_b2bpo_media_VideoBrowser
#define _Included_com_b2bpo_media_VideoBrowser
#ifdef __cplusplus
extern "C" {
#endif
#undef com_b2bpo_media_VideoBrowser_DIALOG_LOAD_MEDIA
#define com_b2bpo_media_VideoBrowser_DIALOG_LOAD_MEDIA 1L
#undef com_b2bpo_media_VideoBrowser_DIALOG_HELP
#define com_b2bpo_media_VideoBrowser_DIALOG_HELP 2L
/*
 * Class:     com_b2bpo_media_ffmpegTest_VideoBrowser
 * Method:    naRun
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_b2bpo_media_ffmpeg_test_VideoBrowser_naRun
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
